# Generated by Django 2.0.7 on 2018-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20)),
                ('fathername', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.IntegerField(blank=True)),
                ('center', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('birthdate', models.DateField(blank=True, max_length=20)),
                ('feeSubDate', models.DateField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
