# Generated by Django 2.0.7 on 2018-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='managerType',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
