# Generated by Django 2.0.7 on 2018-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0003_paymentmodel_managertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='center',
            new_name='ExMatFee',
        ),
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='lastname',
            new_name='ExamFee',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='termFee',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
