# Generated by Django 2.0.7 on 2018-10-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0005_auto_20181001_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='ExMatFee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ExamFee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='termFee',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
