# Generated by Django 2.0.7 on 2018-10-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0006_auto_20181001_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='termFee',
            new_name='termFeeJan',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='termFeeMay',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='termFeeSep',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
