# Generated by Django 2.0.7 on 2018-10-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0008_auto_20181005_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('m1', models.IntegerField(blank=True)),
                ('m2', models.IntegerField(blank=True)),
                ('m3', models.IntegerField(blank=True)),
                ('m4', models.IntegerField(blank=True)),
                ('m5', models.IntegerField(blank=True)),
                ('m6', models.IntegerField(blank=True)),
                ('m7', models.IntegerField(blank=True)),
                ('m8', models.IntegerField(blank=True)),
                ('m9', models.IntegerField(blank=True)),
                ('m10', models.IntegerField(blank=True)),
                ('m11', models.IntegerField(blank=True)),
                ('m12', models.IntegerField(blank=True)),
                ('status', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='feeLedger',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='idci',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='idCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.center'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='idTranCheckSum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.checker'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='idstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='idbatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='idcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.center'),
        ),
        migrations.AlterField(
            model_name='uploaded',
            name='idTRanCheckSum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.checker'),
        ),
        migrations.AddField(
            model_name='feeregister',
            name='idstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.student'),
        ),
    ]
