# Generated by Django 2.0.7 on 2018-10-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0010_auto_20181006_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
