# Generated by Django 2.0.7 on 2018-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0011_auto_20181006_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
