# Generated by Django 2.0.7 on 2018-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0012_auto_20181006_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='idLevel',
            field=models.IntegerField(blank=True, default=433),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='idlevel_certified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
