# Generated by Django 2.0.7 on 2018-10-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0014_auto_20181006_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='idTRanCheckSum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.checker'),
        ),
    ]
