# Generated by Django 2.0.7 on 2018-10-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0015_auto_20181015_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded',
            name='idTRanCheckSum',
        ),
    ]
