# Generated by Django 2.0.7 on 2018-10-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0019_auto_20181016_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
