# Generated by Django 2.0.7 on 2018-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0020_remove_register_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='managerRegister',
        ),
    ]
