# Generated by Django 2.0.7 on 2018-10-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0021_auto_20181017_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerregister',
            old_name='manager',
            new_name='batch',
        ),
    ]
