# Generated by Django 2.0.7 on 2018-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0022_auto_20181018_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
