# Generated by Django 2.0.7 on 2018-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0023_batch_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
