# Generated by Django 2.0.7 on 2018-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0025_auto_20181021_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='feeType',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
