# Generated by Django 2.0.7 on 2018-10-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0026_auto_20181022_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feereceipt',
            name='comment',
        ),
    ]
