# Generated by Django 2.0.7 on 2018-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0028_center_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center',
        ),
        migrations.AddField(
            model_name='batch',
            name='centerName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
