# Generated by Django 2.0.7 on 2018-10-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0030_managerregister_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerregister',
            old_name='user_id',
            new_name='user',
        ),
    ]
